In [41]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pickle

# Load the breast cancer dataset
cancer = load_breast_cancer()

# Allocate training data 80% and test data 20%
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.2, random_state=0)

## Decision Tree Classifier

In [42]:
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.model_selection import cross_validate
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# initialize DT classifier
clf = DecisionTreeClassifier()

# train the model
clf.fit(X_train, y_train)

# export the decision tree in text format
r = export_text(clf, feature_names=cancer.feature_names.tolist())

# show decision tree
# print(r)

# save model using pickle
with open('models/decisionTreeClassifier.pkl', 'wb') as file:
    pickle.dump(clf, file)

# predict datasets with model
predictions = clf.predict(X_test)

# evaluate metrics
accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
f1 = f1_score(y_test, predictions)
cm = confusion_matrix(y_test, predictions)

# measure model's performance using 10-fold cross validation
cv = cross_validate(clf, cancer.data, cancer.target, cv=10, scoring=['accuracy', 'f1'])

# show metrics
print('Accuracy: ', accuracy)
print('Precision: ', precision)
print('Recall: ', recall)
print('F1: ', f1)
print('Confusion Matrix:\n', cm)

# show cross validation metrics
print('Cross Validation Accuracy:\n', cv['test_accuracy'])
print('Cross Validation F1:\n', cv['test_f1'])

Accuracy:  0.9035087719298246
Precision:  0.9516129032258065
Recall:  0.8805970149253731
F1:  0.9147286821705426
Confusion Matrix:
 [[44  3]
 [ 8 59]]
Cross Validation Accuracy:
 [0.89473684 0.85964912 0.9122807  0.84210526 0.94736842 0.89473684
 0.84210526 0.94736842 0.9122807  0.94642857]
Cross Validation F1:
 [0.91428571 0.88888889 0.93150685 0.87323944 0.95890411 0.91666667
 0.87671233 0.95774648 0.92537313 0.95522388]


## ID3 Estimator

In [ ]:
from id3 import Id3Estimator, export_graphviz
import numpy as np


## K Means

In [ ]:
from sklearn.cluster import KMeans
import numpy as np

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

## Neural Network - Multi-layer Perceptron (MLP) Classifier

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification

## Support Vector Machine

In [ ]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
import numpy as np

# Load the dataset
data = np.array([[60, 1.6, 0], [55, 1.5, 0], [65, 1.7, 1], [70, 1.8, 1], [80, 1.9, 1], [50, 1.4, 0], [75, 1.85, 1]])

# Split the data into input (X) and output (y) variables
X = data[:, :2]
y = data[:, 2]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print("X_train:\n", X_train)
print("X_test:\n", X_test)
print("y_train:\n", y_train)
print("y_test:\n", y_test)


X_train:
 [[60.    1.6 ]
 [65.    1.7 ]
 [80.    1.9 ]
 [75.    1.85]]
X_test:
 [[70.   1.8]
 [50.   1.4]
 [55.   1.5]]
y_train:
 [0. 1. 1. 1.]
y_test:
 [1. 0. 0.]
